# Generated by Django 4.2.14 on 2024-08-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Booking",
            new_name="Reservation",
        ),
    ]
