# Generated by Django 4.2.14 on 2024-09-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_user_last_login_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default=True, max_length=128),
        ),
    ]
